name: Build OpenWrt

on:
  push:
    branches:
      - openwrt-21.02
  pull_request:
    branches:
      - openwrt-21.02
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: openwrt-21.02

      - name: Show git config
        run: |
          git config --list
          git branch -a

      - name: Set up Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc binutils bzip2 flex python3 perl make grep unzip swig gawk subversion libz-dev libc-dev rsync libncurses5-dev libncursesw5-dev libpam0g-dev liblzma-dev libsnmp-dev libnetfilter-queue-dev liblzma-dev libpam0g-dev

      - name: Compile OpenWrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make -j$(nproc)

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: openwrt-build
          path: |
            bin/targets/rockchip/armv8/**
          if-no-files-found: error
          exclude: |
            bin/targets/rockchip/armv8/packages/**

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: "OpenWrt Build ${{ github.sha }}"
          draft: false
          prerelease: false

      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/targets/rockchip/armv8/
          asset_name: openwrt-armv8-build-${{ github.sha }}.tar.gz
          asset_content_type: application/gzip
